"use client";

import { useState } from "react";
import Link from "next/link";
import { useQuery } from "@tanstack/react-query";
import { Loader2 } from "lucide-react";

import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { InstrumentSelector, type InstrumentSymbol } from "@/components/shared/instrument-selector";
import { StatusBadge } from "@/components/shared/status-badge";
import { TimeframeSelector } from "@/components/shared/timeframe-selector";
import { getInstrument, getTradeSetups } from "@/lib/api";
import { formatPrice, formatTimestamp } from "@/lib/utils";
import type { Direction, Timeframe, TradeSetupStatus } from "@/types";

const STATUS_OPTIONS: { value: TradeSetupStatus | "all"; label: string }[] = [
  { value: "all", label: "All statuses" },
  { value: "pending", label: "Pending" },
  { value: "triggered", label: "Triggered" },
  { value: "expired", label: "Expired" },
  { value: "invalidated", label: "Invalidated" },
];

const DIRECTION_OPTIONS: { value: Direction | "all"; label: string }[] = [
  { value: "all", label: "All directions" },
  { value: "bullish", label: "Bullish" },
  { value: "bearish", label: "Bearish" },
];

export default function SetupsPage() {
  const [symbol, setSymbol] = useState<InstrumentSymbol>("NQ");
  const [timeframe, setTimeframe] = useState<Timeframe>("15m");
  const [direction, setDirection] = useState<Direction | "all">("all");
  const [status, setStatus] = useState<TradeSetupStatus | "all">("all");

  const { data: instrument } = useQuery({
    queryKey: ["instrument", symbol],
    queryFn: () => getInstrument(symbol),
  });

  const {
    data: setups,
    isLoading,
    error,
  } = useQuery({
    queryKey: ["trade-setups", instrument?.id, timeframe, direction, status],
    queryFn: () =>
      getTradeSetups({
        instrument_id: instrument!.id,
        timeframe,
        direction: direction === "all" ? undefined : direction,
        status: status === "all" ? undefined : status,
      }),
    enabled: !!instrument,
  });

  return (
    <div className="mx-auto max-w-6xl p-6">
      <h1 className="text-xl font-semibold">Qualified Setup Review</h1>
      <p className="mt-1 text-sm text-muted-foreground">
        Trade setups generated by the execution model framework.
      </p>

      <Card className="mt-4">
        <CardHeader>
          <CardTitle>Filters</CardTitle>
        </CardHeader>
        <CardContent className="grid grid-cols-2 gap-4 sm:grid-cols-4">
          <div className="flex flex-col gap-1">
            <label className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Instrument</label>
            <InstrumentSelector value={symbol} onChange={setSymbol} />
          </div>
          <div className="flex flex-col gap-1">
            <label className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Timeframe</label>
            <TimeframeSelector value={timeframe} onChange={setTimeframe} />
          </div>
          <div className="flex flex-col gap-1">
            <label className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Direction</label>
            <Select value={direction} onValueChange={(v) => setDirection(v as Direction | "all")}>
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {DIRECTION_OPTIONS.map((o) => (
                  <SelectItem key={o.value} value={o.value}>
                    {o.label}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
          <div className="flex flex-col gap-1">
            <label className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Status</label>
            <Select value={status} onValueChange={(v) => setStatus(v as TradeSetupStatus | "all")}>
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {STATUS_OPTIONS.map((o) => (
                  <SelectItem key={o.value} value={o.value}>
                    {o.label}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
        </CardContent>
      </Card>

      <Card className="mt-4">
        <CardHeader className="flex-row items-center justify-between">
          <CardTitle>Setups {setups ? `(${setups.length})` : ""}</CardTitle>
          {isLoading ? <Loader2 className="h-4 w-4 animate-spin text-muted-foreground" /> : null}
        </CardHeader>
        <CardContent>
          {error ? <div className="text-sm text-bearish">{(error as Error).message}</div> : null}
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Setup ID</TableHead>
                <TableHead>Date</TableHead>
                <TableHead>Direction</TableHead>
                <TableHead>Entry</TableHead>
                <TableHead>Stop</TableHead>
                <TableHead>Target</TableHead>
                <TableHead>RR</TableHead>
                <TableHead>Status</TableHead>
                <TableHead>Source Execution Model</TableHead>
                <TableHead />
              </TableRow>
            </TableHeader>
            <TableBody>
              {(setups ?? []).map((s) => (
                <TableRow key={s.id}>
                  <TableCell className="font-mono text-xs">{s.id.slice(0, 8)}</TableCell>
                  <TableCell className="whitespace-nowrap">{formatTimestamp(s.created_at)}</TableCell>
                  <TableCell>
                    <StatusBadge status={s.direction} />
                  </TableCell>
                  <TableCell className="tabular-nums">{formatPrice(s.entry_price)}</TableCell>
                  <TableCell className="tabular-nums">{formatPrice(s.stop_price)}</TableCell>
                  <TableCell className="tabular-nums">{formatPrice(s.target_price)}</TableCell>
                  <TableCell className="tabular-nums">{formatPrice(s.rr_ratio)}</TableCell>
                  <TableCell>
                    <StatusBadge status={s.status} />
                  </TableCell>
                  <TableCell className="font-mono text-xs">
                    {s.execution_model_evaluation_id ? s.execution_model_evaluation_id.slice(0, 8) : "—"}
                  </TableCell>
                  <TableCell>
                    <Button size="sm" variant="outline" asChild>
                      <Link href={`/setups/${s.id}`}>View</Link>
                    </Button>
                  </TableCell>
                </TableRow>
              ))}
              {!isLoading && (setups ?? []).length === 0 ? (
                <TableRow>
                  <TableCell colSpan={10} className="text-center text-sm text-muted-foreground">
                    No trade setups found for this filter combination.
                  </TableCell>
                </TableRow>
              ) : null}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  );
}
